In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import numpy as np
from hidmed import *
from tqdm import tqdm
import matplotlib.pyplot as plt

In [3]:
xdim, zdim, wdim, mdim, udim = 1, 1, 1, 1, 1
for setup in ["a", "b", "c"]:
    print(setup)
    datagen = LinearHidMedDGP(xdim, zdim, wdim, mdim, udim, setup=setup, seed=0)
    print(datagen.true_psi())
    print(datagen.diagnostics())

a
1.5288949197529045
(0.054896346688630644, 0.9603479795649502)
b
-0.49286919666747864
(0.022130431788334248, 0.9784680809142835)
c
0.26949896611810986
(0.022130431788334248, 0.9784680809142835)


In [4]:
xdim, zdim, wdim, mdim, udim = 5, 2, 2, 2, 1
for setup in ["a", "b", "c"]:
    print(setup)
    datagen = LinearHidMedDGP(xdim, zdim, wdim, mdim, udim, setup=setup, seed=0)
    print(datagen.true_psi())
    print(datagen.diagnostics())

a
1.4499499899112276
(0.2187158438750789, 0.784770155325153)
b
0.733662299986601
(0.1923582503046849, 0.8233959160137242)
c
1.4593042719375737
(0.1923582503046849, 0.8233959160137242)


In [3]:
n = 200
xdim = 1
zdim = 1
wdim = 1
mdim = 1
udim = 1

setup = "c"
datagen = LinearHidMedDGP(xdim, zdim, wdim, mdim, udim, setup=setup, seed=0)
print(datagen.true_psi())
print(datagen.diagnostics())

[0.26949897]
(0.022130431788334248, 0.9784680809142835)


In [4]:
for i in range(1):
    dataset = datagen.sample_dataset(n, seed=i)
    for method in [
        ProximalOutcomeRegression,
        # ProximalInverseProbWeighting,
        # ProximalMultiplyRobust,
    ]:
        est = method(
            generalized_model=(setup == "b" or setup == "c"),
            kernel_metric="rbf",
            folds=1,
            num_runs=200,
            n_jobs=1,
        )
        estimate = est.fit(dataset)
        print(method, estimate, "\n")

==== Cross-fitting fold 1 (100/100 fit/eval)
Treatment prob params: {'C': 0.058, 'degree': 1} log_loss:  0.687
Bridge h params: {'lambda1': 1.8e-06, 'lambda2': 2e-07, 'gamma': 0.001} score:  -0.2697666
eta params: {'alpha': 0.0, 'gamma': 0.034} r2:  0.985
==== Estimate 1: 1.3366854542458253
<class 'hidmed.por.ProximalOutcomeRegression'> 1.3366854542458253 



In [6]:
dataset = datagen.sample_dataset(n, seed=i)
estimator = ProximalOutcomeRegression(
    generalized_model=(setup == "b" or setup == "c"),
    kernel_metric="rbf",
    folds=1,
    num_runs=200,
    n_jobs=1,
    # **est.params,
)
estimate = est.fit(dataset)

==== Cross-fitting fold 1 (100/100 fit/eval)
Treatment prob params: {'C': 0.058, 'degree': 1} log_loss:  nan
Bridge h params: {'lambda1': 1.8e-06, 'lambda2': 2e-07, 'gamma': 0.001} score:  nan
eta params: {'alpha': 0.0, 'gamma': 0.034} r2:  nan
==== Estimate 1: 1.3366854542458253


In [12]:
estimator = ProximalOutcomeRegression(
    generalized_model=(setup == "b" or setup == "c"),
    kernel_metric="rbf",
    folds=2,
    num_runs=200,
    n_jobs=1,
    # **est.params,
)
estimate = estimator.fit(dataset)

==== Cross-fitting fold 1 (67/134 fit/eval)
Treatment prob params: {'C': 1000000.0, 'degree': 2} log_loss:  0.641
Bridge h params: {'lambda1': 0.1, 'lambda2': 0.1, 'gamma': 0.001} score:  -0.0296634
eta params: {'alpha': 0.016, 'gamma': 0.159} r2:  0.981
==== Estimate 1: 0.6701537725029394
==== Cross-fitting fold 2 (67/134 fit/eval)
Treatment prob params: {'C': 1000000.0, 'degree': 2} log_loss:  nan
Bridge h params: {'lambda1': 0.1, 'lambda2': 0.1, 'gamma': 0.001} score:  nan
eta params: {'alpha': 0.016, 'gamma': 0.159} r2:  nan
==== Estimate 2: 0.6714272492119463


In [ ]:
setup = "b"
datagen = LinearHidMedDGP(xdim, zdim, wdim, mdim, udim, setup=setup, seed=0)

print(datagen.true_psi())
print(datagen.diagnostics())

for i in range(1):
    dataset = datagen.sample_dataset(n, seed=i)
    for method in [
        # ProximalOutcomeRegression,
        # ProximalInverseProbWeighting,
        ProximalMultiplyRobust,
    ]:
        est = method(
            generalized_model=(setup == "b" or setup == "c"),
            kernel_metric="rbf",
            folds=1,
            num_runs=200,
            n_jobs=1,
        )
        estimate = est.fit(dataset)
        print(method, estimate, "\n")

(array([-0.4928692]), 0.04150455843052382)
(0.022130431788334248, 0.9784680809142835)
==== Cross-fitting fold 1 (2000/2000 fit/eval)
Bridge h params: {'lambda1': 7e-06, 'lambda2': 0.0190296, 'gamma': 9e-07} score:  -0.000422
Treatment prob params: {'C': 0.015, 'degree': 2} log_loss:  0.658
Bridge q params: {'lambda1': 1.68e-05, 'lambda2': 2.2e-06, 'gamma': 0.0154611} score:  0.1244815
eta params: {'alpha': 0.002, 'gamma': 0.01} r2:  0.989
==== Estimate 1: -0.25877362091987754
<class 'hidmed2.pmr.ProximalMultiplyRobust'> -0.25877362091987754 



In [ ]:
setup = "b"
datagen = LinearHidMedDGP(xdim, zdim, wdim, mdim, udim, setup=setup, seed=0)

print(datagen.true_psi())
print(datagen.diagnostics())

for i in range(1):
    dataset = datagen.sample_dataset(n, seed=i)
    for method in [
        # ProximalOutcomeRegression,
        ProximalInverseProbWeighting,
        # ProximalMultiplyRobust,
    ]:
        est = method(
            generalized_model=(setup == "b" or setup == "c"),
            kernel_metric="rbf",
            folds=1,
            num_runs=200,
            n_jobs=1,
        )
        estimate = est.fit(dataset)
        print(method, estimate, "\n")

(array([-0.4928692]), 0.04150455843052382)
(0.022130431788334248, 0.9784680809142835)
==== Cross-fitting fold 1 (2000/2000 fit/eval)
Bridge q params: {'lambda1': 1e-07, 'lambda2': 0.0279407, 'gamma': 1.28e-05} score:  -0.0138943
==== Estimate 1: 0.06444304732517314
<class 'hidmed2.pipw.ProximalInverseProbWeighting'> 0.06444304732517314 



In [ ]:
setup = "c"
datagen = LinearHidMedDGP(xdim, zdim, wdim, mdim, udim, setup=setup, seed=0)

print(datagen.true_psi())
print(datagen.diagnostics())

for i in range(1):
    dataset = datagen.sample_dataset(n, seed=i)
    for method in [
        # ProximalOutcomeRegression,
        # ProximalInverseProbWeighting,
        ProximalMultiplyRobust,
    ]:
        est = method(
            generalized_model=(setup == "b" or setup == "c"),
            kernel_metric="rbf",
            folds=1,
            num_runs=200,
            n_jobs=1,
        )
        estimate = est.fit(dataset)
        print(method, estimate, "\n")

(array([0.26949897]), 0.8038727212161121)
(0.022130431788334248, 0.9784680809142835)
==== Cross-fitting fold 1 (2000/2000 fit/eval)
Bridge h params: {'lambda1': 0.0454318, 'lambda2': 1e-07, 'gamma': 0.0016697} score:  0.2790513
Treatment prob params: {'C': 0.016, 'degree': 2} log_loss:  0.658
Bridge q params: {'lambda1': 0.0008065, 'lambda2': 1e-07, 'gamma': 6.4238985} score:  89376.0358505
eta params: {'alpha': 0.008, 'gamma': 0.025} r2:  0.99
==== Estimate 1: 0.4766600386140055
<class 'hidmed2.pmr.ProximalMultiplyRobust'> 0.4766600386140055 



In [ ]:
setup = "c"
datagen = LinearHidMedDGP(xdim, zdim, wdim, mdim, udim, setup=setup, seed=0)

print(datagen.true_psi())
print(datagen.diagnostics())

for i in range(1):
    dataset = datagen.sample_dataset(n, seed=i)
    for method in [
        # ProximalOutcomeRegression,
        ProximalInverseProbWeighting,
        # ProximalMultiplyRobust,
    ]:
        est = method(
            generalized_model=(setup == "b" or setup == "c"),
            kernel_metric="rbf",
            folds=1,
            num_runs=200,
            n_jobs=1,
        )
        estimate = est.fit(dataset)
        print(method, estimate, "\n")

(array([0.26949897]), 0.8038727212161121)
(0.022130431788334248, 0.9784680809142835)
==== Cross-fitting fold 1 (2000/2000 fit/eval)
Bridge q params: {'lambda1': 2.4e-06, 'lambda2': 4.3e-06, 'gamma': 6e-07} score:  39.0508075
==== Estimate 1: 0.300072622844817
<class 'hidmed2.pipw.ProximalInverseProbWeighting'> 0.300072622844817 



In [ ]:
est.params

{'q': {'lambda1': 9.999999999999994e-08,
  'lambda2': 0.027940714334350955,
  'gamma': 1.2836610470082075e-05}}

In [ ]:
est = ProximalInverseProbWeighting(
    generalized_model=(setup == "b" or setup == "c"),
    lambda_q=9.999999999999994e-08,
    lambda_qf=0.027940714334350955,
    gamma=1.2836610470082075e-05,
    folds=1,
    num_runs=200,
)
estimate = est.fit(dataset)

==== Cross-fitting fold 1 (2000/2000 fit/eval)
